# image: node:latest

# stages:
#   - build
#   - test

# cache:
#   paths:
#     - node_modules/

# install_dependencies:
#   stage: build
#   script:
#     - npm install

# testing:
#   stage: test
#   script: npm run test:ci


image: node:latest
# Defines the steps
stages:
  - build
  - test
  - containerization
  - deploy

# add to keep the packages in the process.
cache:
  paths:
    - node_modules/

building:
  stage: build
  script:
    - npm install

# testing:
#   dependencies: 
#     - building
#   stage: test
#   script: npm run test:ci

containerization:
  image: docker:latest
  #image: gitlab/dind
  stage: containerization # must match the stage name declared above
  services:
    - docker:dind
  before_script:
    # Add docker-hub credentials 
    #- docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_USER" --password-stdin
  script:
    #- systemctl start docker
    # Build the container image
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    #- docker build --pull -t docker_app .
    # Add Tag
    - docker tag "$CI_REGISTRY_IMAGE" "$DOCKER_HUB_USER"/"$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
    #- docker tag docker_app yairmontes/docker_app
    # Push the container image to the registry
    #- docker push yairmontes/docker_app
    - docker push "$DOCKER_HUB_USER"/"$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
    # Cleanup by removing the local image
    #- docker image rm yairmontes/"$CI_REGISTRY_IMAGE"
  #variables to deploy -- new
  variables:
  #    DOCKER_HOST: tcp://localhost:2375
      DOCKER_TLS_CERTDIR: ""


deployment:
    stage: deploy
    image: lwolf/helm-kubectl-docker:v152_213
    before_script:
      - mkdir -p /etc/deploy
      - echo ${kube_config} | base64 -d > ${KUBECONFIG}
      - kubectl config use-context homekube
      - helm init --client-only
      - helm repo add stable https://kubernetes-charts.storage.googleapis.com/
      - helm repo add incubator https://kubernetes-charts-incubator.storage.googleapis.com/
      - helm repo update
    script:
      - cd deploy/libr-files
      - helm dep build
      - export API_VERSION="$(grep "appVersion" Chart.yaml | cut -d" " -f2)"
      - export RELEASE_NAME="libr-files-v${API_VERSION/./-}"
      - export DEPLOYS=$(helm ls | grep $RELEASE_NAME | wc -l)
      - if [ ${DEPLOYS}  -eq 0 ]; then helm install --name=${RELEASE_NAME} . --namespace=${STAGING_NAMESPACE}; else helm upgrade ${RELEASE_NAME} . --namespace=${STAGING_NAMESPACE}; fi
    environment:
      name: staging
      url: https://librerio.example.com
    only:
    - master

# deployment:
#   stage: deploy # must match the stage name declared above
#   image: bitnami/kubectl:1.14
#   script:
#     - kubectl get deploment hola-node || kubectl create deployment hola-node --image="$DOCKER_HUB_USER"/"$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
#     - kubectl set image deployment/hola-node hola-node="$DOCKER_HUB_USER"/"$CI_REGISTRY_IMAGE":"$CI_COMMIT_SHA"
#     # create/update the kubernetes resources
#     #- kubectl apply -f kubernetes_manifest.yml
#     # Restart the deployment so as to pull the latest version of the container image
#     #- kubectl rollout restart deployment/docker_app
#   only: 
#     - master
#   environment:
#     name: production
