# image: node:latest

# stages:
#   - build
#   - test

# cache:
#   paths:
#     - node_modules/

# install_dependencies:
#   stage: build
#   script:
#     - npm install

# testing:
#   stage: test
#   script: npm run test:ci


image: node:latest
stages:
  - build
  - containerization
#  - deploy

testing:
  stage: build
  script: npm run test:ci
  
containerization:
  stage: containerization # must match the stage name declared above
  image: gitlab/dind
  script:
    # Add docker-hub credentials 
    - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
    # Build the container image
    - docker build -t docker_app .
    # Add Tag
    - docker tag docker_app yairmontes/docker_app
    # Push the container image to the registry
    - docker push yairmontes/docker_app
    # Cleanup by removing the local image
    #- docker image rm yairmontes/docker_app

# deployment:
#   stage: deploy # must match the stage name declared above
#   script:
#     # create/update the kubernetes resources
#     - kubectl apply -f kubernetes_manifest.yml
#     # Restart the deployment so as to pull the latest version of the container image
#     - kubectl rollout restart deployment/docker_app
#   environment:
#     name: production
