# This section will create a deployment in the Kubernetes cluster
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-app
  #namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-app
      #bb: web
  template:
    metadata:
      labels:
        app: docker-app
        #bb: web
    spec:
      containers:
      - name: docker-app
        image: yairmontes/docker-app:latest
        imagePullPolicy: Always
        command: [ "echo", "IMAGE UPDATED!" ]
        ports:
        - containerPort: 80
---
# This section will create a service in the Kubernetes cluster
# so that the deployment can be accessed from the outside
apiVersion: v1
kind: Service
metadata:
  name: docker-app
  #name: docker-app-entrypoint
  #namespace: default
# spec:
#   ports:
#   - port: 80
#     nodePort: 31234
#   selector:
#     app: docker-app
#   type: NodePort
spec:
  type: LoadBalancer
  selector:
      app: docker-app
      #bb: web
  ports:
    - port: 80
      targetPort: 80
      nodePort: 3000
      #protocol: TCP
      #name: http
